AppPrivy.WebAppSiteBlog/Areas/Admin/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppPrivy.WebAppSiteBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AppPrivy.WebAppSiteBlog/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppPrivy.WebAppSiteBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AppPrivy.WebAppSiteBlog/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppPrivy.WebAppSiteBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        // GET: PostController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PostController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PostController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PostController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PostController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PostController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PostController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AppPrivy.WebAppSiteBlog/Areas/Admin/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppPrivy.WebAppSiteBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TagController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AppPrivy.WebAppSiteBlog/Areas/Admin/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2019</strong>
  
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.5
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

AppPrivy.WebAppSiteBlog/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Área Administrativa</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <environment include="Development">
        <link href="~/admin-lte/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" asp-append-version="true" />
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" asp-append-version="true">
        <!-- Tempusdominus Bbootstrap 4 -->
        <link href="~/admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.css" rel="stylesheet" asp-append-version="true" />
        <!-- iCheck -->
        <link href="~/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <!-- JQVMap -->
        <link href="~/admin-lte/plugins/jqvmap/jqvmap.min.css" rel="stylesheet" asp-append-version="true" />
        <!-- Theme style -->
        <link href="~/admin-lte/dist/css/adminlte.min.css" rel="stylesheet" asp-append-version="true" />
        <!-- overlayScrollbars -->
        <link href="~/admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" rel="stylesheet" asp-append-version="true" />
        <!-- Daterange picker -->
        <link href="~/admin-lte/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" asp-append-version="true" />
        <!-- summernote -->
        <link href="~/admin-lte/plugins/summernote/summernote-bs4.css" rel="stylesheet" asp-append-version="true" />
        <!-- Google Font: Source Sans Pro -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet" asp-append-version="true">
    </environment>

    @RenderSection("Styles", required: false)

</head>

<body class="hold-transition sidebar-mini layout-fixed">

    <div class="wrapper">

        @{await Html.RenderPartialAsync("_NavBar"); }

        @{await Html.RenderPartialAsync("_SideBar"); }

        <div class="content-wrapper">
            @RenderBody()
        </div>

        @{await Html.RenderPartialAsync("_Footer"); }

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="~/admin-lte/plugins/jquery-ui/jquery-ui.min.js" asp-append-version="true"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
            $.widget.bridge('uibutton', $.ui.button)
        </script>
        <!-- Bootstrap 4 -->
        <script src="~/admin-lte/plugins/bootstrap/js/bootstrap.bundle.js" asp-append-version="true"></script>
        <!-- ChartJS -->
        <script src="~/admin-lte/plugins/chart.js/Chart.min.js" asp-append-version="true"></script>
        <!-- Sparkline -->
        <script src="~/admin-lte/plugins/sparklines/sparkline.js" asp-append-version="true"></script>
        <!-- JQVMap -->
        <!--<script src="~/admin-lte/plugins/jqvmap/jquery.vmap.min.js" asp-append-version="true"></script>-->
        <!-- <script src="~/admin-lte/plugins/jqvmap/maps/jquery.vmap.usa.js" asp-append-version="true"></script>-->
        <!-- jQuery Knob Chart -->
        <script src="~/admin-lte/plugins/jquery-knob/jquery.knob.min.js" asp-append-version="true"></script>
        <!-- daterangepicker -->
        <script src="~/admin-lte/plugins/moment/moment.min.js" asp-append-version="true"></script>

        <script src="~/admin-lte/plugins/daterangepicker/daterangepicker.js" asp-append-version="true"></script>
        <!-- Tempusdominus Bootstrap 4 -->
        <script src="~/admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" asp-append-version="true"></script>
        <!-- Summernote -->
        <script src="~/admin-lte/plugins/summernote/summernote-bs4.min.js" asp-append-version="true"></script>
        <!-- overlayScrollbars -->
        <script src="~/admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" asp-append-version="true"></script>
        <!-- AdminLTE App -->
        <script src="~/admin-lte/dist/js/adminlte.js" asp-append-version="true"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <!--<script src="~/admin-lte/dist/js/pages/dashboard.js" asp-append-version="true"></script>-->
        <!-- AdminLTE for demo purposes -->
        <script src="~/admin-lte/dist/js/demo.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)

</body>
</html>

AppPrivy.WebAppSiteBlog/Areas/Admin/Views/Shared/_NavBar.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Home" asp-action="Index" asp-area="Admin" asp-route-returnUrl="/Home/Index" class="nav-link">Home</a>
        </li>

     

        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Home" asp-action="Logout" asp-area="Admin" asp-route-returnUrl="/Identity/Account/Login" class="nav-link">Sair</a>
        </li>
    </ul>
      

    <ul class="navbar-nav ml-auto">  
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

AppPrivy.WebAppSiteBlog/Areas/Admin/Views/Shared/_SideBar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/admin-lte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Área Administrativa</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">


        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/admin-lte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image" />

            </div>
            <div class="info">
                <a href="#" class="d-block">@User.Identity.Name</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                               
                <li class="nav-header">MENU</li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Author" asp-area="Admin" class="nav-link">
                        <i class="nav-icon fas fa-user-alt"></i>
                        <p>Autor</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Category" asp-area="Admin" class="nav-link">
                        <i class="nav-icon far fa-list-alt" ></i>
                        <p>Categoria</p>
                    </a>
                </li>         
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Tag"  asp-area="Admin" class="nav-link">
                        <i class="nav-icon fa fa-tag"></i>
                        <p>Tag</p>
                    </a>
                </li>              
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Post" asp-area="Admin" class="nav-link">
                        <i class="nav-icon 	fas fa-book-open"></i>
                        <p>Post</p>
                    </a>
                </li>             
             
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>